<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.17.0" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" Version="4.17.0" />
    <PackageReference Include="AutoFixture.NUnit3" Version="4.17.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NSubstitute" Version="4.2.1" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\integrations\ordercloud.integrations.exchangerates\ordercloud.integrations.exchangerates.csproj" />
    <ProjectReference Include="..\..\src\Headstart.API\Headstart.API.csproj" />
    <ProjectReference Include="..\..\src\Headstart.Common\Headstart.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Tests\" />
  </ItemGroup>

</Project>
