<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.0.1</Version>
    <Authors>Four51, Inc.</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalara.AvaTax" Version="20.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="6.0.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="6.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ordercloud.integrations.library\ordercloud.integrations.library.csproj" />
  </ItemGroup>

</Project>
